import { useEffect, useMemo, useState } from 'react';
import { BarChart3, BriefcaseBusiness, Calculator, FileCheck2, Megaphone, PiggyBank, Plus, ShieldCheck, Trash2, TrendingDown, TrendingUp } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { PageTour } from '@/components/ui/page-tour';
import { PremiumBadge } from '@/components/premium-badge';

type Entry = { id: string; month: string; type: 'income' | 'expense'; label: string; amount: number };
type BusinessData = {
  hourlyRate: number;
  annualRevenue: number;
  fixedCosts: number;
  microThreshold: number;
  packagePrice: number;
  projectHours: number;
  insurance: boolean;
  entries: Entry[];
};
const storageKey = 'tnp-business';
const defaults: BusinessData = { hourlyRate: 45, annualRevenue: 0, fixedCosts: 0, microThreshold: 77700, packagePrice: 3500, projectHours: 80, insurance: false, entries: [] };

export default function Business() {
  const [data, setData] = useState<BusinessData>(defaults);
  const [entry, setEntry] = useState({ month: new Date().toISOString().slice(0, 7), type: 'income' as Entry['type'], label: '', amount: '' });
  useEffect(() => { try { setData({ ...defaults, ...JSON.parse(localStorage.getItem(storageKey) || '{}') }); } catch { setData(defaults); } }, []);
  const persist = (next: BusinessData) => { setData(next); localStorage.setItem(storageKey, JSON.stringify(next)); };
  const totals = useMemo(() => data.entries.reduce((acc, item) => ({ income: acc.income + (item.type === 'income' ? item.amount : 0), expense: acc.expense + (item.type === 'expense' ? item.amount : 0) }), { income: 0, expense: 0 }), [data.entries]);
  const addEntry = () => { const amount = Number(entry.amount); if (!entry.label || !amount) return; persist({ ...data, entries: [...data.entries, { ...entry, id: `${Date.now()}`, amount }] }); setEntry({ ...entry, label: '', amount: '' }); };
  const removeEntry = (id: string) => persist({ ...data, entries: data.entries.filter((item) => item.id !== id) });
  return <div>
    <PageTour tourKey="business" pageTitle="Business" pageIcon={BriefcaseBusiness} steps={[{ icon: Calculator, title: 'Pilotez votre activité', body: 'Mesurez votre vrai taux horaire, anticipez les mois creux et gardez une vision claire de vos charges.' }]} />
    <div className="relative mb-8 overflow-hidden rounded-2xl hero-gradient-vivid px-8 py-7 ring-1 ring-white/60"><p className="eyebrow mb-2 text-[#a8893e]">Votre activité de wedding planner</p><div className="flex items-center gap-3"><h1 className="font-serif text-[43px] leading-[0.9]">Business</h1><PremiumBadge /></div><p className="mt-3 max-w-2xl text-[11px] leading-relaxed text-muted-foreground">Un espace personnel pour sortir du pilotage au feeling : trésorerie, rentabilité, acquisition et protection.</p></div>
    <div className="grid gap-4 md:grid-cols-4"><Metric icon={PiggyBank} label="Solde suivi" value={`${(totals.income - totals.expense).toLocaleString('fr-FR')} €`} tone="gold" /><Metric icon={Calculator} label="Taux horaire cible" value={`${data.hourlyRate} €/h`} tone="sage" /><Metric icon={TrendingUp} label="CA enregistré" value={`${totals.income.toLocaleString('fr-FR')} €`} tone="rose" /><Metric icon={TrendingDown} label="Marge avant plafond" value={`${Math.max(0, data.microThreshold - data.annualRevenue).toLocaleString('fr-FR')} €`} tone="gold" /></div>
    <div className="mt-6 grid gap-6 xl:grid-cols-[1.4fr_1fr]"><section className="card-depth p-6"><div className="mb-5 flex items-center gap-3"><BarChart3 size={18} className="text-primary" /><div><h2 className="font-serif text-2xl">Trésorerie</h2><p className="text-[10px] text-muted-foreground">Suivez les mois creux avant qu’ils ne vous surprennent.</p></div></div><div className="grid gap-3 sm:grid-cols-5"><Input type="month" value={entry.month} onChange={(e) => setEntry({ ...entry, month: e.target.value })} /><Input placeholder="Libellé" value={entry.label} onChange={(e) => setEntry({ ...entry, label: e.target.value })} /><select value={entry.type} onChange={(e) => setEntry({ ...entry, type: e.target.value as Entry['type'] })} className="h-10 rounded-md border border-input bg-background px-3 text-[11px]"><option value="income">Recette</option><option value="expense">Charge</option></select><Input type="number" placeholder="Montant €" value={entry.amount} onChange={(e) => setEntry({ ...entry, amount: e.target.value })} /><Button onClick={addEntry} className="gap-2"><Plus size={14} /> Ajouter</Button></div><div className="mt-5 space-y-2">{data.entries.length === 0 ? <p className="py-8 text-center text-[11px] text-muted-foreground">Ajoutez vos encaissements et charges mensuels.</p> : data.entries.slice().reverse().map((item) => <div key={item.id} className="flex items-center gap-3 border-b border-border/40 py-3 text-[11px]"><span className={`h-2 w-2 rounded-full ${item.type === 'income' ? 'bg-sage' : 'bg-rose-400'}`} /><span className="flex-1">{item.month} · {item.label}</span><strong className={item.type === 'income' ? 'text-sage' : 'text-destructive'}>{item.type === 'income' ? '+' : '-'}{item.amount} €</strong><button onClick={() => removeEntry(item.id)} className="text-muted-foreground hover:text-destructive"><Trash2 size={13} /></button></div>)}</div></section>
      <section className="card-depth p-6"><h2 className="font-serif text-2xl">Garde-fous</h2><p className="mt-1 text-[10px] text-muted-foreground">Les chiffres qui protègent vos décisions.</p><div className="mt-5 space-y-4"><Setting label="Taux horaire réel minimum" value={data.hourlyRate} suffix="€/h" onChange={(value) => persist({ ...data, hourlyRate: value })} /><Setting label="Charges fixes mensuelles" value={data.fixedCosts} suffix="€" onChange={(value) => persist({ ...data, fixedCosts: value })} /><Setting label="CA annuel déjà sécurisé" value={data.annualRevenue} suffix="€" onChange={(value) => persist({ ...data, annualRevenue: value })} /><Setting label="Plafond micro à surveiller" value={data.microThreshold} suffix="€" onChange={(value) => persist({ ...data, microThreshold: value })} /></div><div className="mt-6 border-t border-border/40 pt-5"><div className="flex items-center gap-3"><ShieldCheck size={18} className={data.insurance ? 'text-sage' : 'text-primary'} /><div className="flex-1"><p className="text-[12px] font-semibold">RC professionnelle</p><p className="text-[10px] text-muted-foreground">{data.insurance ? 'À jour' : 'À vérifier avant la prochaine saison'}</p></div><Button size="sm" variant="outline" onClick={() => persist({ ...data, insurance: !data.insurance })}>{data.insurance ? 'À jour' : 'Marquer vérifiée'}</Button></div></div></section></div>
    <div className="mt-6 grid gap-4 md:grid-cols-3"><Insight icon={TrendingDown} title="Hiver creux" text="Constituez une réserve de 3 mois de charges fixes avant la haute saison." /><Insight icon={Megaphone} title="Acquisition diversifiée" text="Suivez les prospects venant du réseau, du SEO, des partenaires et des plateformes séparément." /><Insight icon={FileCheck2} title="Cadre professionnel" text="Vérifiez plafond de CA, RC pro et clauses de responsabilité en cas de défaillance d’un prestataire." /></div>
    <section className="card-depth mt-6 p-6"><div className="flex items-center gap-3"><Calculator size={18} className="text-primary" /><div><h2 className="font-serif text-2xl">Tester un forfait</h2><p className="text-[10px] text-muted-foreground">Vérifiez votre taux horaire réel avant d’accepter un dossier.</p></div></div><div className="mt-5 grid gap-4 md:grid-cols-3"><Setting label="Prix du forfait" value={data.packagePrice} suffix="€" onChange={(value) => persist({ ...data, packagePrice: value })} /><Setting label="Heures estimées, réunions incluses" value={data.projectHours} suffix="h" onChange={(value) => persist({ ...data, projectHours: value })} /><div className="rounded-xl bg-primary/[0.06] p-4"><p className="text-[10px] text-muted-foreground">Taux réel du dossier</p><p className="mt-1 font-serif text-2xl text-primary">{data.projectHours > 0 ? Math.round(data.packagePrice / data.projectHours) : 0} €/h</p></div></div></section>
  </div>;
}
function Metric({ icon: Icon, label, value, tone }: { icon: typeof PiggyBank; label: string; value: string; tone: string }) { return <div className={`card-depth border-l-4 p-5 ${tone === 'gold' ? 'border-l-[#c8a96e]' : tone === 'sage' ? 'border-l-sage' : 'border-l-rose-300'}`}><Icon size={17} className="mb-4 text-primary" /><p className="text-[10px] uppercase tracking-[0.12em] text-muted-foreground">{label}</p><p className="mt-1 font-serif text-2xl">{value}</p></div>; }
function Setting({ label, value, suffix, onChange }: { label: string; value: number; suffix: string; onChange: (value: number) => void }) { return <label className="block"><span className="mb-1 block text-[10px] text-muted-foreground">{label}</span><div className="flex items-center gap-2"><Input type="number" value={value} onChange={(e) => onChange(Number(e.target.value))} /><span className="text-[11px] text-muted-foreground">{suffix}</span></div></label>; }
function Insight({ icon: Icon, title, text }: { icon: typeof TrendingDown; title: string; text: string }) { return <div className="card-depth p-5"><Icon size={17} className="mb-3 text-primary" /><h3 className="font-serif text-xl">{title}</h3><p className="mt-2 text-[11px] leading-relaxed text-muted-foreground">{text}</p></div>; }