import { useMemo, useState } from 'react';
import { Alert, FlatList, Linking, Platform, StyleSheet, Text, TextInput, TouchableOpacity, View } from 'react-native';
import { LinearGradient } from 'expo-linear-gradient';
import { Feather } from '@expo/vector-icons';
import { useQueryClient } from '@tanstack/react-query';
import { getListAddressBookEntriesQueryKey, useCreateAddressBookEntry, useDeleteAddressBookEntry, useListAddressBookEntries } from '@workspace/api-client-react';
import { useColors } from '@/hooks/useColors';
import { SANS, SANS_SEMIBOLD, SERIF } from '@/constants/fonts';

export default function CarnetAdresseScreen() {
  const colors = useColors(); const insets = Platform.OS === 'web' ? 67 : 0; const queryClient = useQueryClient();
  const { data: entries = [], isLoading } = useListAddressBookEntries(); const create = useCreateAddressBookEntry(); const remove = useDeleteAddressBookEntry();
  const [search, setSearch] = useState(''); const [adding, setAdding] = useState(false); const [form, setForm] = useState({ name: '', category: '', contactName: '', contactEmail: '', contactPhone: '', website: '', notes: '' });
  const filtered = useMemo(() => { const q = search.trim().toLocaleLowerCase(); return q ? entries.filter((e) => [e.name, e.category, e.contactName, e.contactEmail].filter(Boolean).join(' ').toLocaleLowerCase().includes(q)) : entries; }, [entries, search]);
  const submit = () => { if (!form.name.trim() || !form.category.trim()) return; create.mutate({ data: form }, { onSuccess: () => { queryClient.invalidateQueries({ queryKey: getListAddressBookEntriesQueryKey() }); setForm({ name: '', category: '', contactName: '', contactEmail: '', contactPhone: '', website: '', notes: '' }); setAdding(false); }, onError: () => Alert.alert('Erreur', 'Impossible d’enregistrer ce contact.') }); };
  const field = (key: keyof typeof form, placeholder: string) => <TextInput style={[styles.input, { backgroundColor: colors.card, borderColor: colors.border, color: colors.foreground }]} value={form[key]} onChangeText={(value) => setForm({ ...form, [key]: value })} placeholder={placeholder} placeholderTextColor={colors.mutedForeground} />;
  return <View style={{ flex: 1, backgroundColor: colors.background }}>
    <FlatList data={filtered} keyExtractor={(item) => String(item.id)} contentContainerStyle={{ paddingBottom: 140 }} ListHeaderComponent={<>
      <LinearGradient colors={[colors.plumDark, colors.plum, colors.plumLight]} style={[styles.hero, { paddingTop: insets + 28 }]}>
        <View style={styles.heroTop}>
          <View style={styles.heroTitleWrap}>
            <Text style={[styles.eyebrow, { color: colors.gold }]}>VOTRE RÉSEAU DE CONFIANCE</Text>
            <Text style={[styles.title, { color: '#fff', fontFamily: SERIF }]}>Mon carnet d’adresses</Text>
          </View>
          <TouchableOpacity style={styles.heroAdd} onPress={() => setAdding(!adding)} accessibilityLabel={adding ? 'Fermer le formulaire' : 'Ajouter un contact'}>
            <Feather name={adding ? 'x' : 'plus'} size={15} color="#fff" />
            <Text style={[styles.heroAddText, { fontFamily: SANS_SEMIBOLD }]}>{adding ? 'Fermer' : 'Ajouter'}</Text>
          </TouchableOpacity>
        </View>
        <Text style={[styles.body, { color: '#F7EAF4', fontFamily: SANS }]}>Vos prestataires favoris, prêts à être ajoutés à n’importe quel mariage.</Text>
      </LinearGradient>
      <View style={styles.controls}><TextInput style={[styles.input, { flex: 1, backgroundColor: colors.card, borderColor: colors.border, color: colors.foreground }]} value={search} onChangeText={setSearch} placeholder="Rechercher un prestataire…" placeholderTextColor={colors.mutedForeground} /></View>
      {adding && <View style={[styles.form, { backgroundColor: colors.card, borderColor: colors.border }]}>{field('name', 'Nom du prestataire *')}{field('category', 'Catégorie *')}{field('contactName', 'Nom du contact')}{field('contactEmail', 'Email')}{field('contactPhone', 'Téléphone')}{field('website', 'Site internet')}{field('notes', 'Notes')}<TouchableOpacity style={[styles.save, { backgroundColor: colors.plum }]} onPress={submit}><Text style={[styles.saveText, { fontFamily: SANS_SEMIBOLD }]}>Ajouter au carnet</Text></TouchableOpacity></View>}
    </>} renderItem={({ item }) => <View style={[styles.card, { backgroundColor: colors.card, borderColor: colors.border }]}><View style={styles.cardTop}><View style={[styles.avatar, { backgroundColor: colors.gold + '35' }]}><Text style={[styles.avatarText, { color: colors.plum, fontFamily: SERIF }]}>{item.name.split(/\s+/).map((word) => word[0]).join('').slice(0, 2).toUpperCase()}</Text></View><View style={{ flex: 1 }}><Text style={[styles.name, { color: colors.foreground, fontFamily: SANS_SEMIBOLD }]}>{item.name}</Text><Text style={[styles.category, { color: colors.plum, fontFamily: SANS }]}>{item.category}</Text></View><TouchableOpacity onPress={() => Alert.alert('Supprimer ce contact ?', item.name, [{ text: 'Annuler', style: 'cancel' }, { text: 'Supprimer', style: 'destructive', onPress: () => remove.mutate({ id: item.id }, { onSuccess: () => queryClient.invalidateQueries({ queryKey: getListAddressBookEntriesQueryKey() }) }) }])}><Feather name="trash-2" size={16} color={colors.mutedForeground} /></TouchableOpacity></View>{item.contactName && <Info icon="user" value={item.contactName} colors={colors} />}{item.contactEmail && <Info icon="mail" value={item.contactEmail} colors={colors} onPress={() => Linking.openURL(`mailto:${item.contactEmail}`)} />}{item.contactPhone && <Info icon="phone" value={item.contactPhone} colors={colors} />}{item.website && <Info icon="globe" value={item.website} colors={colors} />}{item.notes && <Text style={[styles.notes, { color: colors.mutedForeground, fontFamily: SANS }]}>{item.notes}</Text>}</View>} ListEmptyComponent={<Text style={[styles.empty, { color: colors.mutedForeground, fontFamily: SANS }]}>{isLoading ? 'Chargement…' : entries.length ? 'Aucun contact trouvé.' : 'Votre carnet est encore vide.'}</Text>} showsVerticalScrollIndicator={false} />
  </View>;
}
function Info({ icon, value, colors, onPress }: any) { return <TouchableOpacity disabled={!onPress} onPress={onPress} style={styles.info}><Feather name={icon} size={13} color={colors.mutedForeground} /><Text style={[styles.infoText, { color: colors.mutedForeground, fontFamily: SANS }]} numberOfLines={1}>{value}</Text></TouchableOpacity>; }
const styles = StyleSheet.create({ hero: { padding: 24, paddingBottom: 28, borderBottomLeftRadius: 24, borderBottomRightRadius: 24 }, heroTop: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 12 }, heroTitleWrap: { flex: 1, minWidth: 0 }, heroAdd: { flexDirection: 'row', alignItems: 'center', gap: 5, flexShrink: 0, paddingHorizontal: 10, paddingVertical: 8, borderRadius: 9, backgroundColor: 'rgba(255,255,255,0.14)', borderWidth: StyleSheet.hairlineWidth, borderColor: 'rgba(200,170,112,0.45)' }, heroAddText: { color: '#fff', fontSize: 10 }, eyebrow: { fontSize: 9, letterSpacing: 1.5, marginBottom: 8 }, title: { fontSize: 34, lineHeight: 39 }, body: { marginTop: 12, fontSize: 13, lineHeight: 20 }, controls: { flexDirection: 'row', gap: 9, padding: 16 }, input: { minHeight: 42, borderWidth: 1, borderRadius: 9, paddingHorizontal: 12, fontSize: 12 }, add: { width: 42, height: 42, borderRadius: 9, alignItems: 'center', justifyContent: 'center' }, form: { marginHorizontal: 16, marginBottom: 10, padding: 14, borderWidth: 1, borderRadius: 14, gap: 9 }, save: { minHeight: 42, borderRadius: 9, justifyContent: 'center', alignItems: 'center' }, saveText: { color: '#fff', fontSize: 11 }, card: { marginHorizontal: 16, marginBottom: 10, padding: 15, borderWidth: 1, borderRadius: 14 }, cardTop: { flexDirection: 'row', alignItems: 'center', gap: 11 }, avatar: { width: 44, height: 44, borderRadius: 14, alignItems: 'center', justifyContent: 'center' }, avatarText: { fontSize: 17 }, name: { fontSize: 13 }, category: { marginTop: 3, fontSize: 10, textTransform: 'uppercase', letterSpacing: 1 }, info: { flexDirection: 'row', alignItems: 'center', gap: 8, marginTop: 9 }, infoText: { fontSize: 11, flex: 1 }, notes: { borderTopWidth: 1, borderTopColor: 'rgba(128,128,128,.18)', marginTop: 12, paddingTop: 10, fontSize: 10, lineHeight: 16 }, empty: { textAlign: 'center', padding: 40, fontSize: 13 }, help: { position: 'absolute', right: 18, bottom: 86, width: 42, height: 42, borderRadius: 21, alignItems: 'center', justifyContent: 'center' } });