import { useMemo, useState } from 'react';
import { Alert, FlatList, Linking, Platform, StyleSheet, Text, TextInput, TouchableOpacity, View } from 'react-native';
import { LinearGradient } from 'expo-linear-gradient';
import { Feather } from '@expo/vector-icons';
import { useQueryClient } from '@tanstack/react-query';
import { getListAddressBookEntriesQueryKey, useCreateAddressBookEntry, useDeleteAddressBookEntry, useListAddressBookEntries } from '@workspace/api-client-react';
import { useColors } from '@/hooks/useColors';
import { SANS, SANS_SEMIBOLD, SERIF } from '@/constants/fonts';
import { PremiumBadge } from '@/components/PremiumBadge';
import { PremiumPageGate } from '@/components/PremiumPageGate';
import { useSubscription } from '@/lib/subscription';
import { useLocalization } from '@/context/LocalizationContext';

export default function CarnetAdresseScreen() {
  const colors = useColors(); const insets = Platform.OS === 'web' ? 67 : 0; const queryClient = useQueryClient();
  const { language, t } = useLocalization();
  const copy = language === 'fr' ? { feature: 'votre carnet d’adresses', errorBody: 'Impossible d’enregistrer ce contact.', eyebrow: 'VOTRE RÉSEAU DE CONFIANCE', title: 'Mon carnet d’adresses', close: 'Fermer', add: 'Ajouter', closeForm: 'Fermer le formulaire', addContact: 'Ajouter un contact', body: 'Vos prestataires favoris, prêts à être ajoutés à n’importe quel mariage.', search: 'Rechercher un prestataire…', name: 'Nom du prestataire *', category: 'Catégorie *', contact: 'Nom du contact', email: 'Email', phone: 'Téléphone', website: 'Site internet', notes: 'Notes', save: 'Ajouter au carnet', deleteTitle: 'Supprimer ce contact ?', loading: 'Chargement…', noResults: 'Aucun contact trouvé.', empty: 'Votre carnet est encore vide.' } : { feature: 'your address book', errorBody: 'Unable to save this contact.', eyebrow: 'YOUR TRUSTED NETWORK', title: 'My address book', close: 'Close', add: 'Add', closeForm: 'Close form', addContact: 'Add a contact', body: 'Your favorite vendors, ready to be added to any wedding.', search: 'Search for a vendor…', name: 'Vendor name *', category: 'Category *', contact: 'Contact name', email: 'Email', phone: 'Phone', website: 'Website', notes: 'Notes', save: 'Add to address book', deleteTitle: 'Delete this contact?', loading: 'Loading…', noResults: 'No contacts found.', empty: 'Your address book is empty.' };
  const { isActive: isPremium } = useSubscription();
  const { data: entries = [], isLoading } = useListAddressBookEntries(); const create = useCreateAddressBookEntry(); const remove = useDeleteAddressBookEntry();
  const [search, setSearch] = useState(''); const [adding, setAdding] = useState(false); const [form, setForm] = useState({ name: '', category: '', contactName: '', contactEmail: '', contactPhone: '', website: '', notes: '' });
  const filtered = useMemo(() => { const q = search.trim().toLocaleLowerCase(); return q ? entries.filter((e) => [e.name, e.category, e.contactName, e.contactEmail].filter(Boolean).join(' ').toLocaleLowerCase().includes(q)) : entries; }, [entries, search]);
  const submit = () => { if (!form.name.trim() || !form.category.trim()) return; create.mutate({ data: form }, { onSuccess: () => { queryClient.invalidateQueries({ queryKey: getListAddressBookEntriesQueryKey() }); setForm({ name: '', category: '', contactName: '', contactEmail: '', contactPhone: '', website: '', notes: '' }); setAdding(false); }, onError: () => Alert.alert(t('common.error'), copy.errorBody) }); };
  const field = (key: keyof typeof form, placeholder: string) => <TextInput style={[styles.input, { backgroundColor: colors.card, borderColor: colors.border, color: colors.foreground }]} value={form[key]} onChangeText={(value) => setForm({ ...form, [key]: value })} placeholder={placeholder} placeholderTextColor={colors.mutedForeground} />;
  if (!isPremium) return <PremiumPageGate featureLabel={copy.feature} />;
  return <View style={{ flex: 1, backgroundColor: colors.background }}>
    <FlatList data={filtered} keyExtractor={(item) => String(item.id)} contentContainerStyle={{ paddingBottom: 160 }} ListHeaderComponent={<>
      <LinearGradient colors={[colors.plumDark, colors.plum, colors.plumLight]} style={[styles.hero, { paddingTop: insets + 28 }]}>
        <View style={styles.heroTop}>
          <View style={styles.heroTitleWrap}>
            <Text style={[styles.eyebrow, { color: colors.gold }]}>{copy.eyebrow}</Text>
            <View style={styles.titleRow}>
              <Text style={[styles.title, { color: '#fff', fontFamily: SERIF }]}>{copy.title}</Text>
              <PremiumBadge />
            </View>
          </View>
          <TouchableOpacity style={styles.heroAdd} onPress={() => setAdding(!adding)} accessibilityLabel={adding ? copy.closeForm : copy.addContact}>
            <Feather name={adding ? 'x' : 'plus'} size={15} color="#fff" />
            <Text style={[styles.heroAddText, { fontFamily: SANS_SEMIBOLD }]}>{adding ? copy.close : copy.add}</Text>
          </TouchableOpacity>
        </View>
        <Text style={[styles.body, { color: '#F7EAF4', fontFamily: SANS }]}>{copy.body}</Text>
      </LinearGradient>
      <View style={styles.controls}><TextInput style={[styles.input, { flex: 1, backgroundColor: colors.card, borderColor: colors.border, color: colors.foreground }]} value={search} onChangeText={setSearch} placeholder={copy.search} placeholderTextColor={colors.mutedForeground} /></View>
      {adding && <View style={[styles.form, { backgroundColor: colors.card, borderColor: colors.border }]}>{field('name', copy.name)}{field('category', copy.category)}{field('contactName', copy.contact)}{field('contactEmail', copy.email)}{field('contactPhone', copy.phone)}{field('website', copy.website)}{field('notes', copy.notes)}<TouchableOpacity style={[styles.save, { backgroundColor: colors.plum }]} onPress={submit}><Text style={[styles.saveText, { fontFamily: SANS_SEMIBOLD }]}>{copy.save}</Text></TouchableOpacity></View>}
    </>} renderItem={({ item }) => <View style={[styles.card, { backgroundColor: colors.card, borderColor: colors.border }]}><View style={styles.cardTop}><View style={[styles.avatar, { backgroundColor: colors.gold + '35' }]}><Text style={[styles.avatarText, { color: colors.plum, fontFamily: SERIF }]}>{item.name.split(/\s+/).map((word) => word[0]).join('').slice(0, 2).toUpperCase()}</Text></View><View style={{ flex: 1 }}><Text style={[styles.name, { color: colors.foreground, fontFamily: SANS_SEMIBOLD }]}>{item.name}</Text><Text style={[styles.category, { color: colors.plum, fontFamily: SANS }]}>{item.category}</Text></View><TouchableOpacity onPress={() => Alert.alert(copy.deleteTitle, item.name, [{ text: t('common.cancel'), style: 'cancel' }, { text: t('common.delete'), style: 'destructive', onPress: () => remove.mutate({ id: item.id }, { onSuccess: () => queryClient.invalidateQueries({ queryKey: getListAddressBookEntriesQueryKey() }) }) }])}><Feather name="trash-2" size={16} color={colors.mutedForeground} /></TouchableOpacity></View>{item.contactName && <Info icon="user" value={item.contactName} colors={colors} />}{item.contactEmail && <Info icon="mail" value={item.contactEmail} colors={colors} onPress={() => Linking.openURL(`mailto:${item.contactEmail}`)} />}{item.contactPhone && <Info icon="phone" value={item.contactPhone} colors={colors} />}{item.website && <Info icon="globe" value={item.website} colors={colors} />}{item.notes && <Text style={[styles.notes, { color: colors.mutedForeground, fontFamily: SANS }]}>{item.notes}</Text>}</View>} ListEmptyComponent={<Text style={[styles.empty, { color: colors.mutedForeground, fontFamily: SANS }]}>{isLoading ? copy.loading : entries.length ? copy.noResults : copy.empty}</Text>} showsVerticalScrollIndicator={false} />
  </View>;
}
function Info({ icon, value, colors, onPress }: any) { return <TouchableOpacity disabled={!onPress} onPress={onPress} style={styles.info}><Feather name={icon} size={13} color={colors.mutedForeground} /><Text style={[styles.infoText, { color: colors.mutedForeground, fontFamily: SANS }]} numberOfLines={1}>{value}</Text></TouchableOpacity>; }
const styles = StyleSheet.create({ hero: { padding: 24, paddingBottom: 28, borderBottomLeftRadius: 24, borderBottomRightRadius: 24 }, heroTop: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 12 }, heroTitleWrap: { flex: 1, minWidth: 0 }, titleRow: { flexDirection: 'row', alignItems: 'center', gap: 9 }, heroAdd: { flexDirection: 'row', alignItems: 'center', gap: 5, flexShrink: 0, paddingHorizontal: 10, paddingVertical: 8, borderRadius: 9, backgroundColor: 'rgba(255,255,255,0.14)', borderWidth: StyleSheet.hairlineWidth, borderColor: 'rgba(200,170,112,0.45)' }, heroAddText: { color: '#fff', fontSize: 10 }, eyebrow: { fontSize: 9, letterSpacing: 1.5, marginBottom: 8 }, title: { fontSize: 34, lineHeight: 39, flexShrink: 1 }, body: { marginTop: 12, fontSize: 13, lineHeight: 20 }, controls: { flexDirection: 'row', gap: 9, padding: 16 }, input: { minHeight: 42, borderWidth: 1, borderRadius: 9, paddingHorizontal: 12, fontSize: 12 }, add: { width: 42, height: 42, borderRadius: 9, alignItems: 'center', justifyContent: 'center' }, form: { marginHorizontal: 16, marginBottom: 10, padding: 14, borderWidth: 1, borderRadius: 14, gap: 9 }, save: { minHeight: 42, borderRadius: 9, justifyContent: 'center', alignItems: 'center' }, saveText: { color: '#fff', fontSize: 11 }, card: { marginHorizontal: 16, marginBottom: 10, padding: 15, borderWidth: 1, borderRadius: 14 }, cardTop: { flexDirection: 'row', alignItems: 'center', gap: 11 }, avatar: { width: 44, height: 44, borderRadius: 14, alignItems: 'center', justifyContent: 'center' }, avatarText: { fontSize: 17 }, name: { fontSize: 13 }, category: { marginTop: 3, fontSize: 10, textTransform: 'uppercase', letterSpacing: 1 }, info: { flexDirection: 'row', alignItems: 'center', gap: 8, marginTop: 9 }, infoText: { fontSize: 11, flex: 1 }, notes: { borderTopWidth: 1, borderTopColor: 'rgba(128,128,128,.18)', marginTop: 12, paddingTop: 10, fontSize: 10, lineHeight: 16 }, empty: { textAlign: 'center', padding: 40, fontSize: 13 }, help: { position: 'absolute', right: 18, bottom: 86, width: 42, height: 42, borderRadius: 21, alignItems: 'center', justifyContent: 'center' } });