import { useState } from "react";
import {
  Bell, CalendarDays, Check, ChevronRight, CircleUserRound, ClipboardList,
  Clock3, Heart, Home, MoreHorizontal, Search, Users, WalletCards, X
} from "lucide-react";
import "./_group.css";

type Section = "Overview" | "Vendors" | "Timeline" | "Budget" | "Documents";
type Tab = "Home" | "Weddings" | "Vendors" | "Budget" | "Profile";

const weddings = [
  { names: "Sophie & James Hartwell", date: "18 OCT 2024", venue: "The Orangery at Wychwood", image: "/__mockup/images/orangery-hero.jpg", days: "49 DAYS" },
  { names: "Amelia & Theo Laurent", date: "02 NOV 2024", venue: "Villa Edera, Lake Como", image: "/__mockup/images/hartwell-venue.jpg", days: "64 DAYS" },
  { names: "Clara & Henry Whitmore", date: "14 JUN 2025", venue: "The Ned, London", image: "/__mockup/images/orangery-hero.jpg", days: "288 DAYS" },
];
const vendors = [
  { initials: "MF", name: "Maison Floral Studio", category: "Florals & styling", status: "Confirmed", tone: "bg-[#eadfcf]" },
  { initials: "TO", name: "Terrace at One & Only", category: "Catering & bar", status: "Confirmed", tone: "bg-[#dce7df]" },
  { initials: "LC", name: "Lumen & Co. Photography", category: "Photography", status: "Awaiting contract", tone: "bg-[#eadfdf]" },
  { initials: "EP", name: "Élan Press", category: "Stationery", status: "Deposit paid", tone: "bg-[#e1dceb]" },
];
const milestones = [
  { day: "06", month: "SEP", title: "Final menu tasting", detail: "Terrace at One & Only" },
  { day: "12", month: "SEP", title: "Stationery proof approval", detail: "Due to Élan Press" },
  { day: "19", month: "SEP", title: "Ceremony rehearsal", detail: "The Orangery · 17:30" },
];

function Ring({ value, label, color = "#c8aa70" }: { value: number; label: string; color?: string }) {
  const radius = 31;
  const circumference = 2 * Math.PI * radius;
  return <div className="relative h-[82px] w-[82px] shrink-0">
    <svg viewBox="0 0 82 82" className="-rotate-90"><circle cx="41" cy="41" r={radius} fill="none" stroke="#e7e0d7" strokeWidth="5" /><circle cx="41" cy="41" r={radius} fill="none" stroke={color} strokeWidth="5" strokeLinecap="round" strokeDasharray={circumference} strokeDashoffset={circumference * (1 - value / 100)} /></svg>
    <div className="absolute inset-0 flex flex-col items-center justify-center"><span className="font-serif text-[21px] leading-none text-[#263b48]">{value}%</span><span className="mt-1 text-[7px] uppercase tracking-[.12em] text-[#8b837b]">{label}</span></div>
  </div>;
}

export function PremiumMobile() {
  const [tab, setTab] = useState<Tab>("Home");
  const [section, setSection] = useState<Section>("Overview");
  const [wedding, setWedding] = useState(0);
  const [search, setSearch] = useState("");
  const [notice, setNotice] = useState("");
  const [menu, setMenu] = useState(false);
  const notify = (message: string) => { setNotice(message); window.setTimeout(() => setNotice(""), 2200); };
  const active = weddings[wedding];
  const shownVendors = vendors.filter(v => v.name.toLowerCase().includes(search.toLowerCase()) || v.category.toLowerCase().includes(search.toLowerCase()));
  const sections: Section[] = ["Overview", "Vendors", "Timeline", "Budget", "Documents"];

  return <div className="min-h-[100dvh] w-full overflow-x-hidden bg-[#f5f1eb] text-[#263b48]">
    <style>{`@import url('https://fonts.googleapis.com/css2?family=Cormorant+Garamond:wght@400;500;600;700&family=DM+Sans:wght@400;500;600;700&display=swap'); .aurelia-serif{font-family:'Cormorant Garamond',Georgia,serif}.aurelia-sans{font-family:'DM Sans',sans-serif}`}</style>
    <div className="aurelia-sans mx-auto min-h-[100dvh] max-w-[540px] pb-[92px]">
      <header className="sticky top-0 z-30 flex h-[70px] items-center justify-between border-b border-[#ded3c5] bg-[#f8f5ef]/95 px-5 backdrop-blur-md">
        <button aria-label="Profile menu" onClick={() => setMenu(true)} className="flex h-9 w-9 items-center justify-center text-[#52616a]"><CircleUserRound size={20} strokeWidth={1.5}/></button>
        <div className="flex items-center gap-2.5"><span className="flex h-8 w-8 items-center justify-center border border-[#c3a269] aurelia-serif text-[21px] text-[#ab8b52]">A</span><div><p className="aurelia-serif text-[21px] leading-[18px]">Aurelia</p><p className="text-[7px] uppercase tracking-[.22em] text-[#91877b]">Event atelier</p></div></div>
        <button aria-label="Notifications" onClick={() => notify("You have 1 new update")} className="relative flex h-9 w-9 items-center justify-center text-[#52616a]"><Bell size={18} strokeWidth={1.6}/><span className="absolute right-1.5 top-1.5 h-1.5 w-1.5 rounded-full bg-[#b48c4c]"/></button>
      </header>
      <main className="px-5 pt-5">
        <div className="mb-5 flex items-end justify-between"><div><p className="text-[9px] font-semibold uppercase tracking-[.2em] text-[#9b8258]">Good morning, Elise</p><h1 className="aurelia-serif mt-1 text-[28px] leading-[25px]">Your celebrations</h1></div><button onClick={() => notify("All weddings are up to date")} className="flex h-9 w-9 items-center justify-center border border-[#d4c6b6] text-[#8d7554]"><MoreHorizontal size={17}/></button></div>
        <div className="-mx-5 mb-6 flex gap-3 overflow-x-auto px-5 pb-1 [scrollbar-width:none]">
          {weddings.map((item, index) => <button key={item.names} onClick={() => setWedding(index)} className={`relative h-[118px] w-[232px] shrink-0 overflow-hidden rounded-[3px] text-left transition ${wedding === index ? "ring-2 ring-[#c8aa70] ring-offset-2 ring-offset-[#f5f1eb]" : ""}`}><img src={item.image} alt={item.venue} className="absolute inset-0 h-full w-full object-cover"/><div className="absolute inset-0 bg-gradient-to-t from-[#172b35]/90 via-[#263b48]/25 to-transparent"/><span className="absolute right-3 top-3 rounded-full bg-[#f8f2e7]/90 px-2 py-1 text-[8px] font-bold tracking-[.12em] text-[#52616a]">{item.days}</span><div className="absolute bottom-3 left-3 text-[#fffaf0]"><p className="aurelia-serif text-[21px] leading-[19px]">{item.names}</p><p className="mt-1 text-[8px] uppercase tracking-[.14em] text-[#ded8cb]">{item.date} · {item.venue}</p></div></button>)}
        </div>
        <section className="relative mb-6 h-[218px] overflow-hidden rounded-[4px] bg-[#263b48] text-[#f8f3ea] shadow-[0_12px_28px_rgba(38,59,72,.15)]"><img src={active.image} alt={active.venue} className="absolute inset-0 h-full w-full object-cover opacity-65"/><div className="absolute inset-0 bg-gradient-to-t from-[#1b313b] via-[#263b48]/35 to-transparent"/><div className="relative flex h-full flex-col justify-between p-5"><div className="flex justify-between"><div><p className="text-[9px] uppercase tracking-[.22em] text-[#d6bd87]">The celebration</p><p className="aurelia-serif mt-2 max-w-[210px] text-[28px] leading-[25px]">{active.names}</p></div><div className="aurelia-countdown-pulse rounded-full border border-[#d6bd87]/60 px-3 py-2 text-center"><p className="aurelia-serif text-[26px] leading-[21px] text-[#e0c990]">{active.days.split(" ")[0]}</p><p className="text-[7px] uppercase tracking-[.13em] text-[#eee8dc]">days away</p></div></div><div className="flex items-end justify-between border-t border-[#a4aaa3]/35 pt-3"><div><p className="text-[11px] font-medium">{active.venue}</p><p className="mt-1 text-[9px] text-[#c4cbc8]">{active.date} · 126 guests</p></div><Heart size={16} className="text-[#d6bd87]"/></div></div></section>
        <div className="mb-7 flex gap-2 overflow-x-auto pb-1 [scrollbar-width:none]">{sections.map(item => <button key={item} onClick={() => setSection(item)} className={`shrink-0 rounded-full border px-4 py-2 text-[10px] font-semibold transition ${section === item ? "border-[#263b48] bg-[#263b48] text-[#f8f3ea]" : "border-[#d7ccbf] bg-[#f8f5ef] text-[#817c75]"}`}>{item}</button>)}</div>
        {section === "Overview" && <><section className="mb-8"><div className="mb-4 flex items-end justify-between"><div><p className="text-[9px] font-semibold uppercase tracking-[.19em] text-[#9b8258]">At a glance</p><h2 className="aurelia-serif mt-1 text-[26px] leading-none">The essentials</h2></div><span className="text-[9px] text-[#938b82]">30 Aug 2024</span></div><div className="grid grid-cols-2 gap-3"><div className="flex items-center justify-between rounded-[4px] bg-[#faf8f5] p-4"><div><p className="text-[9px] uppercase tracking-[.14em] text-[#8b837b]">Guests</p><p className="aurelia-serif mt-1 text-[29px]">126</p><p className="text-[9px] text-[#718c7f]">2 RSVPs outstanding</p></div><Users size={19} className="text-[#c8aa70]"/></div><div className="flex items-center justify-between rounded-[4px] bg-[#faf8f5] p-4"><div><p className="text-[9px] uppercase tracking-[.14em] text-[#8b837b]">Days until</p><p className="aurelia-serif mt-1 text-[29px]">49</p><p className="text-[9px] text-[#718c7f]">On track for October</p></div><CalendarDays size={19} className="text-[#c8aa70]"/></div><div className="flex items-center gap-3 rounded-[4px] bg-[#faf8f5] p-3"><Ring value={76} label="budget"/><div><p className="text-[9px] uppercase tracking-[.14em] text-[#8b837b]">Committed</p><p className="aurelia-serif mt-1 text-[20px]">£45,430</p><p className="text-[9px] text-[#8b837b]">of £60,000</p></div></div><div className="flex items-center gap-3 rounded-[4px] bg-[#faf8f5] p-3"><Ring value={78} label="complete" color="#718c7f"/><div><p className="text-[9px] uppercase tracking-[.14em] text-[#8b837b]">Tasks done</p><p className="aurelia-serif mt-1 text-[20px]">78%</p><p className="text-[9px] text-[#967346]">12 to review</p></div></div></div></section>
          <section className="mb-8"><div className="mb-4 flex items-end justify-between"><div><p className="text-[9px] font-semibold uppercase tracking-[.19em] text-[#9b8258]">The weeks ahead</p><h2 className="aurelia-serif mt-1 text-[26px] leading-none">Upcoming</h2></div><button onClick={() => setSection("Timeline")} className="text-[9px] font-semibold uppercase tracking-[.13em] text-[#8d7554]">View all</button></div><div className="overflow-hidden rounded-[4px] bg-[#faf8f5]">{milestones.map((item, index) => <button key={item.title} onClick={() => notify(`${item.title} opened`)} className="flex w-full items-center gap-3 border-b border-[#e5ddd2] px-3 py-3.5 text-left last:border-0"><div className={`flex h-11 w-11 shrink-0 flex-col items-center justify-center ${index === 0 ? "bg-[#eee2c8]" : index === 1 ? "bg-[#eadfdf]" : "bg-[#dce7df]"}`}><span className="aurelia-serif text-[20px] leading-[18px]">{item.day}</span><span className="text-[8px] font-bold tracking-[.1em] text-[#887d73]">{item.month}</span></div><div className="min-w-0 flex-1"><p className="truncate text-[11px] font-semibold">{item.title}</p><p className="mt-1 truncate text-[10px] text-[#898c89]">{item.detail}</p></div><ChevronRight size={14} className="text-[#b18b51]"/></button>)}</div></section>
          <section className="mb-8"><div className="mb-4 flex items-end justify-between"><div><p className="text-[9px] font-semibold uppercase tracking-[.19em] text-[#9b8258]">Carefully chosen</p><h2 className="aurelia-serif mt-1 text-[26px] leading-none">Vendor team</h2></div><button onClick={() => setSection("Vendors")} className="text-[9px] font-semibold uppercase tracking-[.13em] text-[#8d7554]">Manage</button></div><div className="grid gap-3">{vendors.slice(0, 3).map(v => <button key={v.name} onClick={() => notify(`${v.name} opened`)} className="flex items-center gap-3 rounded-[4px] bg-[#faf8f5] p-3 text-left shadow-[0_3px_12px_rgba(65,56,45,.04)]"><span className={`flex h-10 w-10 shrink-0 items-center justify-center rounded-full aurelia-serif text-[15px] text-[#52616a] ${v.tone}`}>{v.initials}</span><span className="min-w-0 flex-1"><span className="block truncate text-[11px] font-semibold">{v.name}</span><span className="mt-1 block text-[9px] text-[#898c89]">{v.category}</span></span><span className={`shrink-0 rounded-full px-2 py-1 text-[8px] font-semibold ${v.status === "Confirmed" ? "bg-[#dce8df] text-[#5d7968]" : "bg-[#f0e2cb] text-[#967346]"}`}>{v.status}</span></button>)}</div></section></>}
        {section === "Vendors" && <section><div className="mb-5"><p className="text-[9px] uppercase tracking-[.19em] text-[#9b8258]">The creative team</p><h2 className="aurelia-serif mt-1 text-[30px]">Your vendors</h2></div><div className="relative mb-4"><Search size={16} className="absolute left-3 top-3 text-[#9a938a]"/><input value={search} onChange={e => setSearch(e.target.value)} placeholder="Search vendors or categories" className="h-10 w-full rounded-full border border-[#d7ccbf] bg-[#faf8f5] pl-9 pr-4 text-[10px] outline-none placeholder:text-[#9a938a]"/></div><div className="grid gap-3">{shownVendors.map(v => <button key={v.name} onClick={() => notify(`${v.name} opened`)} className="flex items-center gap-3 rounded-[4px] bg-[#faf8f5] p-4 text-left"><span className={`flex h-11 w-11 items-center justify-center rounded-full aurelia-serif text-[16px] ${v.tone}`}>{v.initials}</span><span className="flex-1"><span className="block text-[12px] font-semibold">{v.name}</span><span className="mt-1 block text-[10px] text-[#898c89]">{v.category}</span></span><ChevronRight size={15} className="text-[#b18b51]"/></button>)}</div></section>}
        {section !== "Overview" && section !== "Vendors" && <section className="rounded-[4px] bg-[#faf8f5] p-5"><p className="text-[9px] uppercase tracking-[.19em] text-[#9b8258]">Aurelia workspace</p><h2 className="aurelia-serif mt-2 text-[31px]">{section}</h2><p className="mt-2 text-[11px] leading-relaxed text-[#7e8584]">A focused view of the Hartwell celebration, ready for your next decision.</p><div className="mt-6 space-y-3">{(section === "Timeline" ? milestones : section === "Budget" ? [{title:"£45,430 committed"}, {title:"£14,570 remaining"}] : [{title:"Contracts & files"}, {title:"Client notes"}]).map(item => <button key={item.title} onClick={() => notify("Workspace item opened")} className="flex w-full items-center justify-between border-b border-[#e5ddd2] pb-3 text-left text-[11px]">{item.title}<ChevronRight size={14} className="text-[#ab8b52]"/></button>)}</div></section>}
      </main>
    </div>
    <nav className="fixed bottom-0 left-0 right-0 z-30 mx-auto flex h-[76px] max-w-[540px] items-start justify-around border-t border-[#d9cebf] bg-[#f8f5ef]/95 px-2 pt-3 backdrop-blur-md">{[{label:"Home",icon:Home,section:"Overview"},{label:"Weddings",icon:Heart,section:"Overview"},{label:"Vendors",icon:Users,section:"Vendors"},{label:"Budget",icon:WalletCards,section:"Budget"},{label:"Profile",icon:CircleUserRound,section:"Documents"}].map(({label,icon:Icon,section:item}) => <button key={label} onClick={() => {setTab(label as Tab); setSection(item as Section)}} className={`flex min-w-[54px] flex-col items-center gap-1 text-[9px] ${tab === label ? "text-[#8d6f3f]" : "text-[#89908d]"}`}><Icon size={18} strokeWidth={tab === label ? 2 : 1.5}/><span>{label}</span>{tab === label && <span className="mt-0.5 h-0.5 w-3 bg-[#b18b51]"/>}</button>)}</nav>
    {menu && <div className="fixed inset-0 z-50 bg-[#1e3039]/35" onClick={() => setMenu(false)}><div className="absolute bottom-0 left-0 right-0 mx-auto max-w-[540px] rounded-t-[22px] bg-[#f8f5ef] p-5 pb-9" onClick={e => e.stopPropagation()}><div className="mb-5 flex items-center justify-between"><div><p className="text-[9px] uppercase tracking-[.2em] text-[#9b8258]">Aurelia</p><p className="aurelia-serif text-[27px]">Elise Carter</p></div><button onClick={() => setMenu(false)}><X size={18}/></button></div><button onClick={() => {setMenu(false);notify("Profile settings opened")}} className="flex w-full justify-between border-y border-[#ded3c5] py-4 text-left text-[11px]">Profile settings<ChevronRight size={14}/></button><button onClick={() => {setMenu(false);notify("Notifications are all clear")}} className="flex w-full justify-between border-b border-[#ded3c5] py-4 text-left text-[11px]">Notifications<Check size={14} className="text-[#718c7f]"/></button></div></div>}
    {notice && <div className="fixed bottom-[88px] left-1/2 z-50 flex -translate-x-1/2 items-center gap-2 whitespace-nowrap bg-[#263b48] px-4 py-3 text-[10px] text-[#f8f3ea] shadow-xl"><Check size={14} className="text-[#d4bd8d]"/>{notice}</div>}
  </div>;
}